added task 4.3
Daria-Donina/Homework pull request #13
Opened 2018-11-15 17:05 UTC by Daria-Donina

2018-11-22 11:36 UTC, yurii-litvinov requested changes

2018-11-22 11:36 UTC, yurii-litvinov commented on sem1/hw4/hw4.3/hw4.3/hw4.3/commands.cpp
> +};
Надо, чтобы структура объявлялась только в одном месте программы, иначе мы в одном месте поменяли, в другм забыли --- и всё сломалось. Эта структура в принципе хранит только данные, с которыми все хотят работать, поэтому её можно в заголовочном файле объявить, потом подключать повсюду.

2018-11-22 11:36 UTC, yurii-litvinov commented on sem1/hw4/hw4.3/hw4.3/hw4.3/auxiliary.cpp
> +	for (int i = 1; i <= size; ++i)
А чего нумерация с 1 начинается? В С++ же принято с 0.

2018-11-22 11:36 UTC, yurii-litvinov commented on sem1/hw4/hw4.3/hw4.3/hw4.3/interface.cpp
> +			else if (isPhoneNumber(phonebook, record.phoneNumber, size))
Так мы дважды просматриваем всю телефонную книгу, чтобы два раза узнать одно и то же. Это не критично, потому что телефонная книга маленькая, но этого легко избежать.

2018-11-22 11:36 UTC, yurii-litvinov commented on sem1/hw4/hw4.3/hw4.3/hw4.3/main.cpp
> +	copyDataToStruct(phonebookFile, phonebook, size);
Лучше было сначала проверить, открылся ли файл, а потом уже вызывать эту функцию

2018-11-22 11:36 UTC, yurii-litvinov commented on sem1/hw4/hw4.3/hw4.3/hw4.3/main.cpp
> +	fclose(phonebookFile);
Мы же внутри userInterface пытаемся открыть этот же файл на запись. И вообще, держать его открытым вроде как нет нужды

2018-11-22 11:36 UTC, yurii-litvinov commented on sem1/hw4/hw4.3/hw4.3/hw4.3/test.cpp
> +		return false;
Так файл не будет закрыт

2018-11-22 12:26 UTC, Daria-Donina commented on sem1/hw4/hw4.3/hw4.3/hw4.3/auxiliary.cpp
> +	for (int i = 1; i <= size; ++i)
Я хотела соответствия "индекс массива - номер записи", поэтому вообще не работала с первым элементом

2018-11-30 08:02 UTC, yurii-litvinov approved these changes
Да, в целом всё ок, зачтена

2018-11-30 08:02 UTC, yurii-litvinov commented on sem1/hw4/hw4.3/hw4.3/hw4.3/main.cpp
> +		FILE * phonebookFile = fopen("phonebook.txt", "w+");
Тут объявляется новый phonebookFile, так что несмотря на то, что файл создаётся, phonebookFile из строки 21 остаётся nullptr и программа падает. Помогло бы убрать отсюда `FILE *`

2018-11-30 08:30 UTC, merged