added task 2.2
Daria-Donina/Homework pull request #43
Opened 2019-03-10 11:23 UTC by Daria-Donina

2019-04-02 19:43 UTC, yurii-litvinov requested changes

2019-04-02 19:43 UTC, yurii-litvinov commented on sem2/hw2/HashTable/HashTable.Tests/HashTableTest.cs
> +            hashTable.Clear();
В общем-то, незачем делать Clear вначале, всё равно перед тестом запустится Initialize, который создаст новую пустую таблицу

2019-04-02 19:43 UTC, yurii-litvinov commented on sem2/hw2/HashTable/HashTable.Tests/ListTest.cs
> +            Assert.AreEqual(list.GetValue(1), 3);
Наоборот, сначала expected

2019-04-02 19:43 UTC, yurii-litvinov commented on sem2/hw2/HashTable/HashTable/HashTable.cs
> +            List[] newBuckets = new List[size];
var

2019-04-02 19:43 UTC, yurii-litvinov commented on sem2/hw2/HashTable/HashTable/HashTable.cs
> +            return !Equals(position, -1);
А чего не просто position != -1?

2019-04-02 19:43 UTC, yurii-litvinov commented on sem2/hw2/HashTable/HashTable/HashTable.cs
> +        }
А если до этого было несколько ресайзов, размер bucket-ов же не вернётся к исходному? Это вполне может быть осознанное решение, но надо пояснить, почему (в комментарии).

2019-04-02 19:43 UTC, yurii-litvinov commented on sem2/hw2/HashTable/HashTable/IHashTable.cs
> +    interface IHashTable
Подозреваю, что это интерфейс ради интерфейса :)

2019-04-06 11:46 UTC, Daria-Donina commented on sem2/hw2/HashTable/HashTable/HashTable.cs
> +        }
Возможно, потому что время выполнения основных операций в среднем не изменится с увеличением размера хеш-таблицы?

2019-04-06 14:52 UTC, yurii-litvinov commented on sem2/hw2/HashTable/HashTable/HashTable.cs
> +        }
Да, но занимаемая ею память-то увеличится. Кидаем в таблицу миллион элементов, делаем clear --- а она всё равно занимает сколько-то мегабайт.

2019-04-06 14:55 UTC, yurii-litvinov approved these changes
Всё ок, зачтена

2019-04-14 13:29 UTC, merged